# fly.toml app configuration file for satellite-dashboard
app = 'satellite-dashboard'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
  cpus = 1
  cpu_kind = 'shared'

